/**
 * Emoji dataset for the reaction picker. Native Unicode, no dependency, no remote source
 * (sovereign). Each entry carries French keywords so the search can match. This is a broad
 * curated subset covering everyday use, organized by category.
 */
export type Emoji = { e: string; k: string };

export type EmojiCategory = {
  id: string;
  label: string;
  /** Emoji used as the category tab glyph. */
  icon: string;
  emojis: Emoji[];
};

/** Quick-access reactions shown as a shortcut row (Discord-style). */
export const QUICK_REACTIONS = ["👍", "❤️", "😂", "🎉", "👌"];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Émotions",
    icon: "😀",
    emojis: [
      { e: "😀", k: "sourire content" },
      { e: "😃", k: "sourire joie" },
      { e: "😄", k: "rire joie" },
      { e: "😁", k: "sourire dents" },
      { e: "😆", k: "rire" },
      { e: "😅", k: "rire sueur gene" },
      { e: "🤣", k: "explose rire" },
      { e: "😂", k: "pleure rire larmes" },
      { e: "🙂", k: "sourire leger" },
      { e: "🙃", k: "envers ironie" },
      { e: "😉", k: "clin oeil" },
      { e: "😊", k: "content timide" },
      { e: "😇", k: "ange innocent" },
      { e: "🥰", k: "amour coeurs" },
      { e: "😍", k: "amour yeux coeur" },
      { e: "🤩", k: "etoiles wow admiration" },
      { e: "😘", k: "bisou coeur" },
      { e: "😗", k: "bisou" },
      { e: "😚", k: "bisou ferme" },
      { e: "😙", k: "bisou sourire" },
      { e: "🥲", k: "sourire larme" },
      { e: "😋", k: "miam langue" },
      { e: "😛", k: "langue" },
      { e: "😜", k: "langue clin" },
      { e: "🤪", k: "fou dingue" },
      { e: "😝", k: "langue yeux fermes" },
      { e: "🤑", k: "argent riche" },
      { e: "🤗", k: "calin" },
      { e: "🤭", k: "gene main bouche" },
      { e: "🤫", k: "chut silence" },
      { e: "🤔", k: "reflechit pense" },
      { e: "🤐", k: "bouche cousue" },
      { e: "🤨", k: "sceptique doute" },
      { e: "😐", k: "neutre" },
      { e: "😑", k: "sans expression" },
      { e: "😶", k: "silence sans bouche" },
      { e: "😏", k: "malin sourire coin" },
      { e: "😒", k: "agace blase" },
      { e: "🙄", k: "yeux ciel agace" },
      { e: "😬", k: "grimace gene" },
      { e: "🤥", k: "menteur" },
      { e: "😌", k: "soulage calme" },
      { e: "😔", k: "deprime triste" },
      { e: "😪", k: "fatigue endormi" },
      { e: "🤤", k: "bave" },
      { e: "😴", k: "dort sommeil" },
      { e: "😷", k: "masque malade" },
      { e: "🤒", k: "malade thermometre" },
      { e: "🤕", k: "blesse bandage" },
      { e: "🤢", k: "nausee degout" },
      { e: "🤮", k: "vomi" },
      { e: "🤧", k: "eternue mouchoir" },
      { e: "🥵", k: "chaud transpire" },
      { e: "🥶", k: "froid gele" },
      { e: "🥴", k: "etourdi ivre" },
      { e: "😵", k: "sonne ko" },
      { e: "🤯", k: "cerveau explose choc" },
      { e: "🤠", k: "cowboy" },
      { e: "🥳", k: "fete anniversaire" },
      { e: "😎", k: "cool lunettes" },
      { e: "🤓", k: "geek intello" },
      { e: "🧐", k: "monocle observe" },
      { e: "😕", k: "confus" },
      { e: "😟", k: "inquiet" },
      { e: "🙁", k: "triste leger" },
      { e: "😮", k: "surpris bouche" },
      { e: "😯", k: "etonne" },
      { e: "😲", k: "choque" },
      { e: "😳", k: "rougit gene" },
      { e: "🥺", k: "suppliant yeux" },
      { e: "😦", k: "consterne" },
      { e: "😧", k: "angoisse" },
      { e: "😨", k: "peur" },
      { e: "😰", k: "anxieux sueur" },
      { e: "😥", k: "triste soulage" },
      { e: "😢", k: "pleure larme" },
      { e: "😭", k: "pleure sanglot" },
      { e: "😱", k: "crie peur" },
      { e: "😖", k: "confus souffre" },
      { e: "😣", k: "persevere" },
      { e: "😞", k: "decu" },
      { e: "😓", k: "sueur froide" },
      { e: "😩", k: "las fatigue" },
      { e: "😫", k: "epuise" },
      { e: "🥱", k: "baille ennui" },
      { e: "😤", k: "enerve fier" },
      { e: "😡", k: "colere rouge" },
      { e: "😠", k: "enerve fache" },
      { e: "🤬", k: "jure insulte" },
      { e: "😈", k: "diable malicieux" },
      { e: "👿", k: "diable colere" },
      { e: "💀", k: "mort crane" },
      { e: "💩", k: "caca" },
      { e: "🤡", k: "clown" },
      { e: "👻", k: "fantome" },
      { e: "👽", k: "alien extraterrestre" },
      { e: "🤖", k: "robot" },
    ],
  },
  {
    id: "gestures",
    label: "Gestes",
    icon: "👍",
    emojis: [
      { e: "👍", k: "pouce bien ok oui approuve" },
      { e: "👎", k: "pouce bas non" },
      { e: "👌", k: "ok parfait" },
      { e: "🤌", k: "doigts italien" },
      { e: "🤏", k: "petit pincee" },
      { e: "✌️", k: "paix victoire" },
      { e: "🤞", k: "doigts croises chance" },
      { e: "🤟", k: "amour signe" },
      { e: "🤘", k: "rock cornes" },
      { e: "🤙", k: "appelle cool" },
      { e: "👈", k: "gauche doigt" },
      { e: "👉", k: "droite doigt" },
      { e: "👆", k: "haut doigt" },
      { e: "👇", k: "bas doigt" },
      { e: "☝️", k: "index haut" },
      { e: "✋", k: "main stop" },
      { e: "🤚", k: "main dos" },
      { e: "🖐️", k: "main doigts" },
      { e: "🖖", k: "vulcain spock" },
      { e: "👋", k: "salut bonjour au revoir" },
      { e: "🤝", k: "poignee main accord deal" },
      { e: "🙏", k: "merci priere stp svp" },
      { e: "✍️", k: "ecrit main" },
      { e: "💅", k: "vernis ongles" },
      { e: "👏", k: "applaudit bravo" },
      { e: "🙌", k: "mains levees hourra" },
      { e: "👐", k: "mains ouvertes" },
      { e: "🤲", k: "mains paume" },
      { e: "💪", k: "muscle force" },
      { e: "🦾", k: "bras mecanique" },
      { e: "👀", k: "yeux regarde" },
      { e: "👁️", k: "oeil" },
      { e: "🫶", k: "coeur mains amour" },
      { e: "🫡", k: "salut militaire" },
      { e: "🫢", k: "surprise main" },
      { e: "🧠", k: "cerveau reflexion" },
    ],
  },
  {
    id: "people",
    label: "Personnes",
    icon: "🧑",
    emojis: [
      { e: "👶", k: "bebe" },
      { e: "🧒", k: "enfant" },
      { e: "👦", k: "garcon" },
      { e: "👧", k: "fille" },
      { e: "🧑", k: "personne adulte" },
      { e: "👨", k: "homme" },
      { e: "👩", k: "femme" },
      { e: "🧓", k: "senior" },
      { e: "👴", k: "grand pere" },
      { e: "👵", k: "grand mere" },
      { e: "🧔", k: "barbe" },
      { e: "👮", k: "police" },
      { e: "🕵️", k: "detective espion" },
      { e: "👷", k: "ouvrier chantier" },
      { e: "👨‍💼", k: "employe bureau" },
      { e: "👩‍💻", k: "developpeuse informatique" },
      { e: "👨‍💻", k: "developpeur informatique" },
      { e: "👨‍🔧", k: "mecanicien" },
      { e: "👩‍🍳", k: "cuisiniere chef" },
      { e: "👨‍🏫", k: "professeur enseignant" },
      { e: "🧑‍🚀", k: "astronaute" },
      { e: "🦸", k: "super heros" },
      { e: "🦹", k: "super vilain" },
      { e: "🧑‍🎨", k: "artiste peintre" },
      { e: "🤵", k: "costume marie" },
      { e: "👰", k: "mariee" },
      { e: "🎅", k: "pere noel" },
      { e: "🧑‍🎄", k: "noel" },
      { e: "🦺", k: "gilet securite" },
      { e: "🏃", k: "court course" },
      { e: "🚶", k: "marche pieton" },
      { e: "💃", k: "danse femme" },
      { e: "🕺", k: "danse homme" },
    ],
  },
  {
    id: "hearts",
    label: "Cœurs",
    icon: "❤️",
    emojis: [
      { e: "❤️", k: "coeur rouge amour" },
      { e: "🧡", k: "coeur orange" },
      { e: "💛", k: "coeur jaune" },
      { e: "💚", k: "coeur vert" },
      { e: "💙", k: "coeur bleu" },
      { e: "💜", k: "coeur violet" },
      { e: "🖤", k: "coeur noir" },
      { e: "🤍", k: "coeur blanc" },
      { e: "🤎", k: "coeur marron" },
      { e: "💔", k: "coeur brise chagrin" },
      { e: "❣️", k: "coeur exclamation" },
      { e: "💕", k: "deux coeurs" },
      { e: "💞", k: "coeurs tournent" },
      { e: "💓", k: "coeur bat" },
      { e: "💗", k: "coeur grandit" },
      { e: "💖", k: "coeur brille" },
      { e: "💘", k: "coeur fleche" },
      { e: "💝", k: "coeur cadeau" },
      { e: "💟", k: "coeur deco" },
      { e: "❤️‍🔥", k: "coeur feu passion" },
      { e: "❤️‍🩹", k: "coeur repare" },
      { e: "💯", k: "cent parfait top" },
      { e: "💋", k: "bisou levres" },
      { e: "💌", k: "lettre amour" },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icon: "🐾",
    emojis: [
      { e: "🐶", k: "chien" },
      { e: "🐱", k: "chat" },
      { e: "🐭", k: "souris" },
      { e: "🐹", k: "hamster" },
      { e: "🐰", k: "lapin" },
      { e: "🦊", k: "renard" },
      { e: "🐻", k: "ours" },
      { e: "🐼", k: "panda" },
      { e: "🐨", k: "koala" },
      { e: "🐯", k: "tigre" },
      { e: "🦁", k: "lion" },
      { e: "🐮", k: "vache" },
      { e: "🐷", k: "cochon" },
      { e: "🐸", k: "grenouille" },
      { e: "🐵", k: "singe" },
      { e: "🐔", k: "poule" },
      { e: "🐧", k: "pingouin" },
      { e: "🐦", k: "oiseau" },
      { e: "🦆", k: "canard" },
      { e: "🦉", k: "hibou" },
      { e: "🐴", k: "cheval" },
      { e: "🦄", k: "licorne" },
      { e: "🐝", k: "abeille" },
      { e: "🐛", k: "chenille" },
      { e: "🦋", k: "papillon" },
      { e: "🐌", k: "escargot" },
      { e: "🐞", k: "coccinelle" },
      { e: "🐢", k: "tortue" },
      { e: "🐍", k: "serpent" },
      { e: "🐙", k: "poulpe" },
      { e: "🦑", k: "calmar" },
      { e: "🦀", k: "crabe" },
      { e: "🐬", k: "dauphin" },
      { e: "🐳", k: "baleine" },
      { e: "🐟", k: "poisson" },
      { e: "🦈", k: "requin" },
      { e: "🐊", k: "crocodile" },
      { e: "🐘", k: "elephant" },
      { e: "🦒", k: "girafe" },
      { e: "🐐", k: "chevre" },
      { e: "🌵", k: "cactus" },
      { e: "🌲", k: "sapin arbre" },
      { e: "🌳", k: "arbre" },
      { e: "🌴", k: "palmier" },
      { e: "🌿", k: "plante feuille" },
      { e: "☘️", k: "trefle" },
      { e: "🍀", k: "trefle chance" },
      { e: "🍁", k: "erable automne" },
      { e: "🍂", k: "feuilles automne" },
      { e: "🌸", k: "fleur cerisier" },
      { e: "🌷", k: "tulipe" },
      { e: "🌹", k: "rose" },
      { e: "🌻", k: "tournesol soleil" },
      { e: "🌼", k: "marguerite" },
      { e: "🌈", k: "arc en ciel" },
      { e: "⭐", k: "etoile favori" },
      { e: "🌟", k: "etoile brille" },
      { e: "✨", k: "etincelles magie" },
      { e: "🔥", k: "feu flamme chaud top" },
      { e: "💧", k: "goutte eau" },
      { e: "🌊", k: "vague mer" },
      { e: "⚡", k: "eclair energie rapide" },
      { e: "☀️", k: "soleil beau temps" },
      { e: "⛅", k: "nuage soleil" },
      { e: "☁️", k: "nuage" },
      { e: "🌙", k: "lune nuit" },
      { e: "❄️", k: "neige flocon froid" },
    ],
  },
  {
    id: "food",
    label: "Nourriture",
    icon: "🍕",
    emojis: [
      { e: "🍏", k: "pomme verte" },
      { e: "🍎", k: "pomme fruit" },
      { e: "🍐", k: "poire" },
      { e: "🍊", k: "orange" },
      { e: "🍋", k: "citron" },
      { e: "🍌", k: "banane" },
      { e: "🍉", k: "pasteque" },
      { e: "🍇", k: "raisin" },
      { e: "🍓", k: "fraise" },
      { e: "🫐", k: "myrtille" },
      { e: "🍒", k: "cerise" },
      { e: "🍑", k: "peche" },
      { e: "🥭", k: "mangue" },
      { e: "🍍", k: "ananas" },
      { e: "🥥", k: "noix coco" },
      { e: "🥝", k: "kiwi" },
      { e: "🍅", k: "tomate" },
      { e: "🥑", k: "avocat" },
      { e: "🥕", k: "carotte" },
      { e: "🌽", k: "mais" },
      { e: "🥔", k: "pomme terre" },
      { e: "🍞", k: "pain" },
      { e: "🥐", k: "croissant" },
      { e: "🥖", k: "baguette" },
      { e: "🧀", k: "fromage" },
      { e: "🥚", k: "oeuf" },
      { e: "🍳", k: "oeuf plat" },
      { e: "🥓", k: "bacon lard" },
      { e: "🍔", k: "burger hamburger" },
      { e: "🍟", k: "frites" },
      { e: "🍕", k: "pizza" },
      { e: "🌭", k: "hot dog" },
      { e: "🥪", k: "sandwich" },
      { e: "🌮", k: "taco" },
      { e: "🌯", k: "burrito" },
      { e: "🥗", k: "salade" },
      { e: "🍝", k: "pates" },
      { e: "🍜", k: "nouilles ramen" },
      { e: "🍣", k: "sushi" },
      { e: "🍤", k: "crevette" },
      { e: "🍚", k: "riz" },
      { e: "🍦", k: "glace" },
      { e: "🍩", k: "donut beignet" },
      { e: "🍪", k: "cookie biscuit" },
      { e: "🎂", k: "gateau anniversaire" },
      { e: "🍰", k: "part gateau" },
      { e: "🧁", k: "cupcake" },
      { e: "🍫", k: "chocolat" },
      { e: "🍬", k: "bonbon" },
      { e: "🍿", k: "popcorn" },
      { e: "☕", k: "cafe the" },
      { e: "🍵", k: "the vert" },
      { e: "🧃", k: "jus brique" },
      { e: "🥤", k: "soda gobelet" },
      { e: "🍺", k: "biere trinque" },
      { e: "🍻", k: "bieres sante" },
      { e: "🍷", k: "vin verre" },
      { e: "🥂", k: "champagne trinque" },
      { e: "🍾", k: "champagne bouteille" },
      { e: "🍸", k: "cocktail" },
    ],
  },
  {
    id: "travel",
    label: "Voyage",
    icon: "✈️",
    emojis: [
      { e: "🚗", k: "voiture" },
      { e: "🚕", k: "taxi" },
      { e: "🚙", k: "suv" },
      { e: "🚌", k: "bus" },
      { e: "🚎", k: "trolley" },
      { e: "🏎️", k: "course voiture" },
      { e: "🚓", k: "police voiture" },
      { e: "🚑", k: "ambulance" },
      { e: "🚒", k: "pompier camion" },
      { e: "🚚", k: "camion" },
      { e: "🚜", k: "tracteur" },
      { e: "🛵", k: "scooter" },
      { e: "🏍️", k: "moto" },
      { e: "🚲", k: "velo" },
      { e: "🛴", k: "trottinette" },
      { e: "🚂", k: "train locomotive" },
      { e: "🚆", k: "train" },
      { e: "🚊", k: "tram" },
      { e: "🚉", k: "gare" },
      { e: "✈️", k: "avion vol" },
      { e: "🛫", k: "decollage" },
      { e: "🛬", k: "atterrissage" },
      { e: "🚀", k: "fusee lance rapide" },
      { e: "🛸", k: "ovni soucoupe" },
      { e: "🚁", k: "helicoptere" },
      { e: "⛵", k: "voilier bateau" },
      { e: "🚤", k: "hors bord" },
      { e: "🛳️", k: "paquebot" },
      { e: "⚓", k: "ancre" },
      { e: "⛽", k: "essence station" },
      { e: "🚦", k: "feu circulation" },
      { e: "🗺️", k: "carte" },
      { e: "🗼", k: "tour" },
      { e: "🏰", k: "chateau" },
      { e: "🗽", k: "liberte statue" },
      { e: "🏝️", k: "ile plage" },
      { e: "🏔️", k: "montagne" },
      { e: "🏕️", k: "camping" },
      { e: "🏠", k: "maison" },
      { e: "🏢", k: "immeuble bureau" },
      { e: "🏭", k: "usine" },
    ],
  },
  {
    id: "activities",
    label: "Activités",
    icon: "⚽",
    emojis: [
      { e: "⚽", k: "foot ballon" },
      { e: "🏀", k: "basket" },
      { e: "🏈", k: "foot americain" },
      { e: "⚾", k: "baseball" },
      { e: "🎾", k: "tennis" },
      { e: "🏐", k: "volley" },
      { e: "🏉", k: "rugby" },
      { e: "🎱", k: "billard" },
      { e: "🏓", k: "ping pong" },
      { e: "🏸", k: "badminton" },
      { e: "🥅", k: "but cage" },
      { e: "⛳", k: "golf" },
      { e: "🏹", k: "tir arc" },
      { e: "🎣", k: "peche" },
      { e: "🥊", k: "boxe" },
      { e: "🥋", k: "judo karate" },
      { e: "⛷️", k: "ski" },
      { e: "🏂", k: "snowboard" },
      { e: "🏋️", k: "musculation" },
      { e: "🤸", k: "gym roue" },
      { e: "🤾", k: "handball" },
      { e: "🏊", k: "natation" },
      { e: "🚴", k: "cyclisme velo" },
      { e: "🧗", k: "escalade" },
      { e: "🏆", k: "trophee gagne victoire" },
      { e: "🥇", k: "or premier medaille" },
      { e: "🥈", k: "argent second" },
      { e: "🥉", k: "bronze troisieme" },
      { e: "🏅", k: "medaille" },
      { e: "🎯", k: "cible objectif" },
      { e: "🎮", k: "jeu manette" },
      { e: "🕹️", k: "joystick arcade" },
      { e: "🎲", k: "des hasard" },
      { e: "♟️", k: "echecs pion" },
      { e: "🎸", k: "guitare musique" },
      { e: "🎹", k: "piano clavier" },
      { e: "🥁", k: "batterie tambour" },
      { e: "🎺", k: "trompette" },
      { e: "🎧", k: "casque musique" },
      { e: "🎤", k: "micro chant" },
      { e: "🎨", k: "peinture art" },
      { e: "🎬", k: "cinema clap" },
      { e: "🎉", k: "fete cotillon bravo" },
      { e: "🎊", k: "confettis fete" },
      { e: "🎈", k: "ballon fete" },
      { e: "🎁", k: "cadeau" },
      { e: "🎆", k: "feu artifice" },
    ],
  },
  {
    id: "objects",
    label: "Objets",
    icon: "💡",
    emojis: [
      { e: "💡", k: "idee ampoule" },
      { e: "🔦", k: "lampe torche" },
      { e: "🔋", k: "batterie" },
      { e: "🔌", k: "prise electrique" },
      { e: "💻", k: "ordinateur laptop" },
      { e: "🖥️", k: "ecran ordinateur" },
      { e: "⌨️", k: "clavier" },
      { e: "🖱️", k: "souris" },
      { e: "🖨️", k: "imprimante" },
      { e: "📱", k: "telephone mobile" },
      { e: "☎️", k: "telephone fixe" },
      { e: "📞", k: "combine appel" },
      { e: "📟", k: "bipeur" },
      { e: "📠", k: "fax" },
      { e: "📷", k: "appareil photo" },
      { e: "📹", k: "camera video" },
      { e: "🎥", k: "camera cinema" },
      { e: "📺", k: "television" },
      { e: "📻", k: "radio" },
      { e: "⏰", k: "reveil alarme" },
      { e: "⏱️", k: "chronometre" },
      { e: "⌚", k: "montre" },
      { e: "📡", k: "antenne satellite" },
      { e: "🔍", k: "loupe recherche" },
      { e: "🔒", k: "cadenas prive verrou" },
      { e: "🔓", k: "cadenas ouvert" },
      { e: "🔑", k: "cle acces" },
      { e: "🗝️", k: "cle ancienne" },
      { e: "🔨", k: "marteau" },
      { e: "🛠️", k: "outils" },
      { e: "⚙️", k: "engrenage reglage" },
      { e: "🧰", k: "boite outils" },
      { e: "🧲", k: "aimant" },
      { e: "💰", k: "argent sac" },
      { e: "💳", k: "carte bancaire" },
      { e: "💵", k: "billet dollar" },
      { e: "🪙", k: "piece monnaie" },
      { e: "📦", k: "colis boite" },
      { e: "📩", k: "enveloppe message" },
      { e: "📨", k: "courrier recu" },
      { e: "✉️", k: "enveloppe mail" },
      { e: "📎", k: "trombone piece jointe" },
      { e: "📌", k: "epingle punaise important" },
      { e: "📍", k: "position lieu" },
      { e: "📅", k: "calendrier date" },
      { e: "📆", k: "calendrier" },
      { e: "📊", k: "graphique barres stats" },
      { e: "📈", k: "hausse graphique" },
      { e: "📉", k: "baisse graphique" },
      { e: "📋", k: "presse papier liste" },
      { e: "📁", k: "dossier fichier" },
      { e: "📂", k: "dossier ouvert" },
      { e: "🗂️", k: "classeur onglets" },
      { e: "📝", k: "note ecrire" },
      { e: "✏️", k: "crayon modifier" },
      { e: "🖊️", k: "stylo" },
      { e: "📚", k: "livres" },
      { e: "📖", k: "livre ouvert" },
      { e: "🔖", k: "marque page signet" },
      { e: "💊", k: "medicament pilule" },
      { e: "🧪", k: "eprouvette chimie" },
      { e: "🔬", k: "microscope" },
      { e: "🧬", k: "adn genetique" },
      { e: "🩺", k: "stethoscope sante" },
    ],
  },
  {
    id: "symbols",
    label: "Symboles",
    icon: "✅",
    emojis: [
      { e: "✅", k: "coche valide fait ok oui" },
      { e: "☑️", k: "case cochee" },
      { e: "✔️", k: "coche" },
      { e: "❌", k: "croix non faux erreur" },
      { e: "❎", k: "croix carre" },
      { e: "➕", k: "plus ajouter" },
      { e: "➖", k: "moins retirer" },
      { e: "➗", k: "division" },
      { e: "✖️", k: "multiplication croix" },
      { e: "🟰", k: "egal" },
      { e: "⚠️", k: "attention avertissement" },
      { e: "🚫", k: "interdit" },
      { e: "❓", k: "question interrogation" },
      { e: "❔", k: "question blanc" },
      { e: "❗", k: "exclamation important" },
      { e: "❕", k: "exclamation blanc" },
      { e: "‼️", k: "double exclamation" },
      { e: "⁉️", k: "exclamation question" },
      { e: "💤", k: "dort sommeil zzz" },
      { e: "💢", k: "colere veine" },
      { e: "💥", k: "explosion boom" },
      { e: "💦", k: "gouttes sueur" },
      { e: "💨", k: "vent rapide fuite" },
      { e: "🕳️", k: "trou" },
      { e: "💬", k: "bulle message" },
      { e: "💭", k: "bulle pensee" },
      { e: "🗯️", k: "bulle colere" },
      { e: "♻️", k: "recyclage" },
      { e: "🔔", k: "cloche notification" },
      { e: "🔕", k: "cloche muet" },
      { e: "🔊", k: "son haut parleur" },
      { e: "🔇", k: "muet son coupe" },
      { e: "📢", k: "annonce megaphone" },
      { e: "➡️", k: "fleche droite suivant" },
      { e: "⬅️", k: "fleche gauche" },
      { e: "⬆️", k: "fleche haut" },
      { e: "⬇️", k: "fleche bas" },
      { e: "🔄", k: "actualiser boucle" },
      { e: "🔝", k: "top haut" },
      { e: "🆕", k: "nouveau new" },
      { e: "🆗", k: "ok accord" },
      { e: "🆒", k: "cool" },
      { e: "🔥", k: "feu tendance" },
      { e: "⭐", k: "etoile favori" },
      { e: "🌟", k: "etoile brillante" },
      { e: "💯", k: "cent parfait" },
      { e: "🚀", k: "fusee rapide" },
      { e: "👑", k: "couronne roi meilleur" },
      { e: "🎯", k: "cible objectif" },
      { e: "💎", k: "diamant precieux" },
      { e: "🏁", k: "arrivee damier" },
    ],
  },
];

/** Flat search over every category by keyword or the emoji itself. */
export function searchEmojis(query: string): Emoji[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: Emoji[] = [];
  const seen = new Set<string>();
  for (const cat of EMOJI_CATEGORIES) {
    for (const em of cat.emojis) {
      if ((em.k.includes(q) || em.e === q) && !seen.has(em.e)) {
        seen.add(em.e);
        out.push(em);
      }
    }
  }
  return out;
}
